//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace LahoreGarrisonUniversity.Models
{
    public partial class Basic
    {
        [Key]
        public string siteTitle { get; set; }
        public string siteDescription { get; set; }
        public string siteURL { get; set; }
        public string siteLogoURI { get; set; }
        public string contactEmail { get; set; }
        public string contactAddress { get; set; }
        public string contactPhone { get; set; }
        public string facebookURL { get; set; }
        public string googleAnalytics { get; set; }
        public string googleMaps { get; set; }
    }
}
