//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace LahoreGarrisonUniversity.Models
{
    using System;

    [Bind(Exclude = "Id,CreatedAt")]
    public partial class News
    {
        [Key,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [ScaffoldColumn(false)]
        public int Id { get; set; }
        
        [DisplayName("Title")]
        public string Title { get; set; }

        [DisplayName("Description")]
        public string Description { get; set; }

        [DisplayName("Media Url")]
        public string MediaUrl { get; set; }

        [DisplayName("Created At")]
        public Nullable<System.DateTime> CreatedAt { get; set; }

        [DisplayName("UserId")]
        public string UserName { get; set; }
    }
}
